name: word_testing
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5+1
  shared_preferences: ^2.0.7
  json_annotation: ^4.0.1
  file_picker: ^4.4.0
  pdf: ^3.6.4
  printing: ^5.6.5
  csv: ^6.0.0
  url_launcher: ^6.3.2
  share_plus: ^3.0.1
  google_fonts: ^2.3.0
  path_provider: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
